
name: nodejs_cache
version: 0.0.1
language: nodejs
description: Cache `./node_modules` directory
public: true
tags:
  - nodejs
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - TRUE
      - FALSE
  - name: FLOW_VERSION
    editable: false
  - name: FLOW_PROJECT_ID
    editable: false
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  